package cn.jxc.pojo;
// Generated 2018-3-14 20:32:32 by Hibernate Tools 5.2.8.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Authority generated by hbm2java
 */
public class Authority implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private int authId;
	private String authName;
	private Date authCreateTime;
	private Set<Object> roleAuths = new HashSet<Object>(0);

	public Authority() {
	}

	public Authority(int authId, String authName, Date authCreateTime) {
		this.authId = authId;
		this.authName = authName;
		this.authCreateTime = authCreateTime;
	}

	public Authority(int authId, String authName, Date authCreateTime, Set<Object> roleAuths) {
		this.authId = authId;
		this.authName = authName;
		this.authCreateTime = authCreateTime;
		this.roleAuths = roleAuths;
	}

	public int getAuthId() {
		return this.authId;
	}

	public void setAuthId(int authId) {
		this.authId = authId;
	}

	public String getAuthName() {
		return this.authName;
	}

	public void setAuthName(String authName) {
		this.authName = authName;
	}

	public Date getAuthCreateTime() {
		return this.authCreateTime;
	}

	public void setAuthCreateTime(Date authCreateTime) {
		this.authCreateTime = authCreateTime;
	}

	public Set<Object> getRoleAuths() {
		return this.roleAuths;
	}

	public void setRoleAuths(Set<Object> roleAuths) {
		this.roleAuths = roleAuths;
	}

}
