package cn.jxc.pojo;
// Generated 2018-3-14 20:32:32 by Hibernate Tools 5.2.8.Final

/**
 * Backsalesdetail generated by hbm2java
 */
public class BackSalesDetail implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private int bsadId;
	private int bsaId;
	private int productId;
	private int count;

	public BackSalesDetail() {
		
	}

	public BackSalesDetail(int bsadId, int bsaId, int productId, int count) {
		this.bsadId = bsadId;
		this.bsaId = bsaId;
		this.productId = productId;
		this.count = count;
	}

	public int getBsadId() {
		return this.bsadId;
	}

	public void setBsadId(int bsadId) {
		this.bsadId = bsadId;
	}

	public int getBsaId() {
		return this.bsaId;
	}

	public void setBsaId(int bsaId) {
		this.bsaId = bsaId;
	}

	public int getProductId() {
		return this.productId;
	}

	public void setProductId(int productId) {
		this.productId = productId;
	}

	public int getCount() {
		return this.count;
	}

	public void setCount(int count) {
		this.count = count;
	}

}
