package cn.jxc.pojo;
// Generated 2018-3-14 20:32:32 by Hibernate Tools 5.2.8.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Leavestock generated by hbm2java
 */
public class LeaveStock implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private String lsId;
	private Employee employee;
	private LeaveStockType leavestocktype;
	private StoreHouse storehouse;
	private Date leaveStockTime;
	private String upstreamNo;
	private Set<LeaveStockDetail> leavestockdetails = new HashSet<LeaveStockDetail>(0);

	public LeaveStock() {
	}

	public LeaveStock(String lsId, Employee employee, LeaveStockType leavestocktype, StoreHouse storehouse,
			Date leaveStockTime, String upstreamNo) {
		this.lsId = lsId;
		this.employee = employee;
		this.leavestocktype = leavestocktype;
		this.storehouse = storehouse;
		this.leaveStockTime = leaveStockTime;
		this.upstreamNo = upstreamNo;
	}

	public LeaveStock(String lsId, Employee employee, LeaveStockType leavestocktype, StoreHouse storehouse,
			Date leaveStockTime, String upstreamNo, Set<LeaveStockDetail> leavestockdetails) {
		this.lsId = lsId;
		this.employee = employee;
		this.leavestocktype = leavestocktype;
		this.storehouse = storehouse;
		this.leaveStockTime = leaveStockTime;
		this.upstreamNo = upstreamNo;
		this.leavestockdetails = leavestockdetails;
	}

	public String getLsId() {
		return this.lsId;
	}

	public void setLsId(String lsId) {
		this.lsId = lsId;
	}

	public Employee getEmployee() {
		return this.employee;
	}

	public void setEmployee(Employee employee) {
		this.employee = employee;
	}

	public LeaveStockType getLeavestocktype() {
		return this.leavestocktype;
	}

	public void setLeavestocktype(LeaveStockType leavestocktype) {
		this.leavestocktype = leavestocktype;
	}

	public StoreHouse getStorehouse() {
		return this.storehouse;
	}

	public void setStorehouse(StoreHouse storehouse) {
		this.storehouse = storehouse;
	}

	public Date getLeaveStockTime() {
		return this.leaveStockTime;
	}

	public void setLeaveStockTime(Date leaveStockTime) {
		this.leaveStockTime = leaveStockTime;
	}

	public String getUpstreamNo() {
		return this.upstreamNo;
	}

	public void setUpstreamNo(String upstreamNo) {
		this.upstreamNo = upstreamNo;
	}

	public Set<LeaveStockDetail> getLeavestockdetails() {
		return this.leavestockdetails;
	}

	public void setLeavestockdetails(Set<LeaveStockDetail> leavestockdetails) {
		this.leavestockdetails = leavestockdetails;
	}

}
