package cn.jxc.pojo;
// Generated 2018-3-14 20:32:32 by Hibernate Tools 5.2.8.Final

/**
 * RoleAuth generated by hbm2java
 */
public class RoleAuth implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private int roleAuthId;
	private Authority authority;
	private Role role;
	private int authId;

	public RoleAuth() {
	}

	public RoleAuth(int roleAuthId, Role role, int authId) {
		this.roleAuthId = roleAuthId;
		this.role = role;
		this.authId = authId;
	}

	public RoleAuth(int roleAuthId, Authority authority, Role role, int authId) {
		this.roleAuthId = roleAuthId;
		this.authority = authority;
		this.role = role;
		this.authId = authId;
	}

	public int getRoleAuthId() {
		return this.roleAuthId;
	}

	public void setRoleAuthId(int roleAuthId) {
		this.roleAuthId = roleAuthId;
	}

	public Authority getAuthority() {
		return this.authority;
	}

	public void setAuthority(Authority authority) {
		this.authority = authority;
	}

	public Role getRole() {
		return this.role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

	public int getAuthId() {
		return this.authId;
	}

	public void setAuthId(int authId) {
		this.authId = authId;
	}

}
